export { default as Header } from './common/Header'
export { default as Footer } from './common/Footer'
export { default as Sidebar } from './common/Sidebar'
export { default as Home } from './Home'
export { default as Document } from './Document'